### ISSUE TITLE
hover

### ISSUE THREAD

**Issue by Aarnachauhan** [Vimall03/Alimento#26]
i would like to add hover to all the buttons and add some animations.

**Comment by Vimall03** [comment]
Hey @Aarnachauhan, I will be assigning this issue to you once you complete issue #24

**Comment by komalnalage** [comment]
Hi @Vimall03  I would like to work on this issue .Could you please assign me this task under the GSSOC-ext and Hacktoberfest-accepted tags? I’m excited to contribute.

Thanks so much!

**Comment by Vimall03** [comment]
Hi @komalnalage, thank you for your interest in this project. However, this issue was opened by another contributor, and we are currently waiting for them to finish their previously assigned issue (#24). If no progress is made, I can assign this issue to you. In the meantime, if you come across any other issues on the site or have ideas for improvements, feel free to open a new issue.

**Comment by BhavikaPachauri** [comment]
I would like to work on this issue. Could you please assign me this task under the GSSOC-ext and Hacktoberfest-accepted tags? I’m excited to contribute.

**Comment by Vimall03** [comment]
Hi @BhavikaPachauri, Thankyou for considering contributing to the project, this issue was opened by another contributor, and we are currently waiting for them to finish their previously assigned issue. If you come across any other issues on the site or have ideas for improvements, feel free to open a new issue.

**Comment by Vimall03** [comment]
@komalnalage, @BhavikaPachauri, Please look into issue #34 & #35 if you guys are still interested in contributing :)

**Comment by BhavikaPachauri** [comment]
> @komalnalage, @BhavikaPachauri, Please look into issue #34 & #35 if you guys are still interested in contributing :)

Okk i am interested in #35

**Comment by Vimall03** [comment]
@BhavikaPachauri I can assign you to #34 as #35 is already assigned. Its pretty much the same issue. if you are interested then comment under issue #34

**Comment by komalnalage** [comment]
I'm interested in #34 can you assign it to me

**Comment by Vimall03** [comment]
@Aarnachauhan, Have you made any progress ?

**Comment by Aarnachauhan** [comment]
Sir , i need 1-2 days as my mid semester exams are going on. I will complete it within 1-2 days . 🙏
Best regards .

**Comment by Vimall03** [comment]
Okay
