### ISSUE TITLE
Adding improvements in Home Page And after navigation 

### ISSUE THREAD

**Issue by aditiverma-21** [Vimall03/Alimento#6]
![image](https://github.com/user-attachments/assets/45dc74d5-e730-4bee-83d5-adffd63b284b)
The website does not refer to any part of the webpage while clicking on about or concept.
![image](https://github.com/user-attachments/assets/409a5e54-4a19-4055-8c6e-871d66b8bf36) for improved user experience the footer must be removed from contact us web page and email must be send to the customer support.

**Comment by Vimall03** [comment]
Hey @aditiverma-21 , thank you so much for your willingness to contribute to this repository! I noticed that this issue seems to be a duplicate of issue #2 . However, if you're interested in taking on the task of redesigning the UI for the entire site, I’d be happy to close this issue and upgrade issue #2  to a level 3. Let me know what you think! 😊

**Comment by aditiverma-21** [comment]
Hello @Vimall03, happy to contribute in this project. yes I am willing to do so

**Comment by Vimall03** [comment]
Sounds great, I'll close this issue.

**Comment by Vimall03** [comment]
Duplicate of #2
