### ISSUE TITLE
[FEAT]:Adding foodlist

### ISSUE THREAD

**Issue by TanviGandhotra** [Vimall03/Alimento#88]
![image](https://github.com/user-attachments/assets/b17dffd3-a862-435a-a299-f87abe9187c1)
![image](https://github.com/user-attachments/assets/3fef5271-d806-4a62-8daf-dbf9073de2cc)
#like the above
i think we can also add veg,non veg type option adnwhen user click we can show him list of that so he get variety

**Comment by Vimall03** [comment]
![image](https://github.com/user-attachments/assets/17918f21-d205-477e-a157-e4b404ccd26e)

I believe that you are opening the project on a live server, Due to which you will only be able to view the html file. This is a PHP project and needs to be opened using a xampp or a wampp server so that you can access all the pages.

> i think we can also add veg,non veg type option adnwhen user click we can show him list of that so he get variety

Talking about this issue, If you login to the site you will notice that we are able to render the menu items and the food type as well. All this is dynamically rendered and changes can be made in the vendor's dashboard (alimento/vendor/home.php) based on the requirement of the restaurant / home chefs.

I'm closing this as unplanned
