### ISSUE TITLE
[FEAT] Sign in page

### ISSUE THREAD

**Issue by poorvikaa08** [Vimall03/Alimento#90]
When clicking the sign-in button on the navbar, it is redirected to save the file.
Also the get started button.

Screenshots 📷 

https://github.com/user-attachments/assets/12d7caa7-ab29-421d-971c-20256337f7d7

when clicked on signup button, this is the observation
![image](https://github.com/user-attachments/assets/a41cedfd-3dde-41ca-acfa-c20999a7df06)

@Vimall03 
I want to create a new sign in page and login page.

**Comment by poorvikaa08** [comment]
@Vimall03 
Review this issue

**Comment by Vimall03** [comment]
Hey @poorvikaa08, The sign in buttons work fine. You are facing this issue because you are either opening the HTML file directly or using a live server. 

Since this is a PHP project, you have to use a XAMPP or a WAMPP server to run the project as expected.

Kindly refer to the set up guidelines in the evening file in the repository.

**Comment by poorvikaa08** [comment]
Okay

**Comment by Vimall03** [comment]
Thank you for your interest in this repository, @poorvikaa08. I have closed this issue. If you find any additional issues you’d like to contribute to, feel free to open a new issue.
