### ISSUE TITLE
[FEAT]: Complete redesign of Track Orders page

### ISSUE THREAD

**Issue by ArchanRD** [Vimall03/Alimento#96]
**Is your feature request related to a problem? Please describe.**
The current design of the order tracking page looks outdated and could be improved for better usability. Users may find it difficult to quickly scan through orders due to the unstructured arrangement and lack of design elements such as icons or improved styling. Additionally, the spacing and alignment feel uneven, making the page look cluttered.

**Describe the solution you'd implement**
I would like to create a modern looking UI design and one which looks more appealing. I can go with 2 options:
1. Enhancing the UI keeping it in table format
2. Show order cards instead of table view. Something similar to the below:

**Describe alternatives you've considered**
1. The standard **Table view**:
Reference image ( somehwhat similar to this not exact ):
![image](https://github.com/user-attachments/assets/614921f6-d6ee-4043-affb-24d5e190045c)

2. Order in form of cards:
![image](https://github.com/user-attachments/assets/2082dd98-79a0-4641-8daa-181f417825dc)

**Additional context**

 I would like to work on this issue under gssoc-ext and hacktoberfest.

**Comment by Vimall03** [comment]
Hey @ArchanRD, We are currently having a complete redesign of of the Client UI in issue #43, Try to merge this PR before the other issue is completed so that we can compare both the designs and go ahead with the better one.

I'll assign this issue level 2, Make sure the PHP script is integrated without any errors to render the orders

**Comment by ArchanRD** [comment]
Done!
